feat(CI): only build/test affected targets

diff --git a/gitlab-ci/config/main.yml b/gitlab-ci/config/main.yml
--- a/gitlab-ci/config/main.yml
+++ b/gitlab-ci/config/main.yml
@@ -149,6 +149,14 @@ bazel-test-coverage:
     - bazel clean --expunge
 
 bazel-test-all:
+  artifacts:
+    when: always
+    paths:
+      - bazel-build-log*.json.gz
+      - bazel-bep.pb
+      - bazel-targets
+    reports:
+      junit: bazel-testlogs-gitlab/**/test.xml
   extends:
     - .bazel-test-all
   rules:
@@ -156,6 +164,7 @@ bazel-test-all:
     - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_TAG =~ /^release-.+/'
   variables:
     BAZEL_EXTRA_ARGS: "--keep_going $BAZEL_EXTRA_ARGS_RULES"
+    RUN_ON_DIFF_ONLY: "true" # only test targets that changed
   timeout: 80 minutes
 
 bazel-system-tests-k8s:
@@ -198,10 +207,10 @@ bazel-system-test-hotfix:
       when: always
     - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "trigger"
       when: manual
-      allow_failure: true  # the pipeline continues running even if the manual job is not run
+      allow_failure: true # the pipeline continues running even if the manual job is not run
     - if: '$CI_MERGE_REQUEST_TITLE =~ /(\[rc\]|hotfix)/i'
       when: manual
-      allow_failure: true  # the pipeline continues running even if the manual job is not run
+      allow_failure: true # the pipeline continues running even if the manual job is not run
     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
       when: manual
       allow_failure: true
@@ -300,29 +309,56 @@ bazel-test-macos:
 
       if [ "$CI_COMMIT_REF_PROTECTED" == "true" ]; then
           gitlab-ci/container/build-ic.sh -i -c -b
+      elif [ "${RUN_ON_DIFF_ONLY:-}" == "true" ] \
+          && [ "${CI_PIPELINE_SOURCE:-}" == "merge_request_event" ] \
+          && [ "${CI_MERGE_REQUEST_EVENT_TYPE:-}" != "merge_train" ] \
+          && [[ "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-}" != "rc--"* ]]; then
+
+          TARGETS=$(gitlab-ci/src/bazel-ci/diff.sh)
+          ARGS=(--no-release)
+
+          if [ "$TARGETS" == "//..." ]; then
+              ARGS+=(-i -c -b)
+          else
+              if grep -q "ic-os" <<<"$TARGETS"; then
+                  ARGS+=(-i)
+              fi
+              if grep -q "publish/canisters" <<<"$TARGETS"; then
+                  ARGS+=(-c)
+              fi
+              if grep -q "publish/binaries" <<<"$TARGETS"; then
+                  ARGS+=(-b)
+              fi
+          fi
+
+          if [ ${#ARGS[@]} -eq 1 ]; then
+              echo "No changes that require building IC-OS, binaries or canisters."
+              exit 0
+          fi
+          gitlab-ci/container/build-ic.sh "${ARGS[@]}"
       else
           gitlab-ci/container/build-ic.sh -i -c -b --no-release
       fi
 
       # release binaries
-      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
+      [ -d artifacts/release ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
           gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
           "artifacts/release" "${CI_JOB_NAME}/release"
       # canister binaries
-      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
+      [ -d artifacts/canisters ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
           gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
           "artifacts/canisters" "${CI_JOB_NAME}/canisters"
 
       # guestos images
-      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
+      [ -d artifacts/icos/guestos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
           gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
           "artifacts/icos/guestos" "${CI_JOB_NAME}/guest-os"
       # hostos images
-      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
+      [ -d artifacts/icos/hostos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
           gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
           "artifacts/icos/hostos" "${CI_JOB_NAME}/host-os"
       # setupos images
-      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
+      [ -d artifacts/icos/setupos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
           gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
           "artifacts/icos/setupos" "${CI_JOB_NAME}/setup-os"
 
@@ -339,6 +375,10 @@ build-ic:
   extends:
     - .build-ic
     - .rules-master-pipeline-no-merge-train
+  variables:
+    # only build binaries, canisters, ic-os if there are changes
+    RUN_ON_DIFF_ONLY: "true"
+    BAZEL_COMMAND: "build"
 
 # Scheduled Pipeline
 build-ic-release:
@@ -534,26 +574,40 @@ build-determinism:
     - .rules-master-pipeline-no-merge-train
   needs:
     - job: bazel-test-all
-      artifacts: false
+      artifacts: true
     - job: build-ic
       artifacts: false
   parallel:
     matrix:
-      - PATH0: "release"
+      - TARGET: "//publish/binaries:upload"
+        PATH0: "release"
         PATH1: "build-ic/release"
-      - PATH0: "canisters"
+      - TARGET: "//publish/canisters:upload"
+        PATH0: "canisters"
         PATH1: "build-ic/canisters"
-      - PATH0: "guest-os/update-img"
+      - TARGET: "//ic-os/guestos/envs/prod:upload_disk-img"
+        PATH0: "guest-os/update-img"
         PATH1: "build-ic/guest-os"
-      - PATH0: "host-os/update-img"
+      - TARGET: "//ic-os/hostos/envs/prod:upload_update-img"
+        PATH0: "host-os/update-img"
         PATH1: "build-ic/host-os"
-      - PATH0: "setup-os/disk-img"
+      - TARGET: "//ic-os/setupos/envs/prod:upload_disk-img"
+        PATH0: "setup-os/disk-img"
         PATH1: "build-ic/setup-os"
         SETUPOS_FLAG: "true"
   script:
     - |
       set -eExuo pipefail
-      ./gitlab-ci/tools/build-diff.sh "$PATH0" "$PATH1"
+
+      # bazel-targets file is expected from bazel-test-all CI job
+      if [ ! -e bazel-targets ]; then
+          echo "Missing 'bazel-targets' file!"
+          exit 1
+      fi
+
+      if grep -q "$TARGET" bazel-targets || grep -qF "//..." bazel-targets; then
+          gitlab-ci/tools/build-diff.sh "$PATH0" "$PATH1"
+      fi
 
 build-determinism-release:
   rules:
