chore(build-ic): push artifacts to ceph's s3

diff --git a/gitlab-ci/config/zz-generated-gitlab-ci.yaml b/gitlab-ci/config/zz-generated-gitlab-ci.yaml
--- a/gitlab-ci/config/zz-generated-gitlab-ci.yaml
+++ b/gitlab-ci/config/zz-generated-gitlab-ci.yaml
@@ -169,6 +169,7 @@
   artifacts:
     paths:
       - bazel-build-log*.json*
+      - build-ic.tar
     reports:
       dotenv: nns.release.env
   needs: []
@@ -235,27 +236,19 @@
           find ./artifacts/icos -name '*.gz' -delete
       fi
 
-      # release binaries
-      [ -d artifacts/release ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/release" "${CI_JOB_NAME}/release"
-      # canister binaries
-      [ -d artifacts/canisters ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/canisters" "${CI_JOB_NAME}/canisters"
+      tar -cf artifacts.tar artifacts
+      URL="http://$(cat /ceph-s3-info/BUCKET_HOST)/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}"
+      curl --request PUT --upload-file artifacts.tar "${URL}/artifacts.tar"
 
-      # guestos images
-      [ -d artifacts/icos/guestos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/icos/guestos" "${CI_JOB_NAME}/guest-os"
-      # hostos images
-      [ -d artifacts/icos/hostos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/icos/hostos" "${CI_JOB_NAME}/host-os"
-      # setupos images
-      [ -d artifacts/icos/setupos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/icos/setupos" "${CI_JOB_NAME}/setup-os"
+      for DIR in release canisters icos/guestos icos/hostos icos/setupos; do
+          mkdir -p "build-ic/${DIR}/"
+          cp "artifacts/${DIR}/SHA256SUMS" "build-ic/${DIR}/"
+      done
+
+      EXTERNAL_URL="https://objects.$(echo "$NODE_NAME" | cut -d'-' -f1)-idx1.dfinity.network/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}/artifacts.tar"
+      echo -e "Node: ${NODE_NAME:-}\nURL: ${URL}\nExternal URL: ${EXTERNAL_URL}" >./build-ic/info
+      echo "${EXTERNAL_URL}" >./build-ic/url
+      tar -cf build-ic.tar build-ic
 
       # clean up
       bazel clean --expunge
@@ -264,9 +257,6 @@
       if [ -f /tmp/nns.release.env ]; then
           mv /tmp/nns.release.env .
       fi
-  tags:
-    - dfinity-ic
-    - bazel
 ".rules-build-base-images":
   rules:
     - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "build-push-base-images"
@@ -1752,7 +1742,7 @@ build-determinism:
   needs:
     - artifacts: true
       job: bazel-test-all
-    - artifacts: false
+    - artifacts: true
       job: build-ic
   parallel:
     matrix:
@@ -1763,14 +1753,14 @@ build-determinism:
         PATH1: build-ic/canisters
         TARGET: "//publish/canisters:upload"
       - PATH0: guest-os/update-img
-        PATH1: build-ic/guest-os
+        PATH1: build-ic/icos/guestos
         TARGET: "//ic-os/guestos/envs/prod:upload_update-img"
       - PATH0: host-os/update-img
-        PATH1: build-ic/host-os
+        PATH1: build-ic/icos/hostos
         TARGET: "//ic-os/hostos/envs/prod:upload_update-img"
-      - PATH0: setup-os/disk-img
-        PATH1: build-ic/setup-os
-        SETUPOS_FLAG: 'true'
+      - DISKIMG: 'true'
+        PATH0: setup-os/disk-img
+        PATH1: build-ic/icos/setupos
         TARGET: "//ic-os/setupos/envs/prod:upload_disk-img"
   rules:
     - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE != "merge_train"
@@ -1786,8 +1776,46 @@ build-determinism:
           exit 1
       fi
 
+      # build-ic.tar with SHA256SUMS files is expected from build-ic CI job
+      if [ ! -e build-ic.tar ]; then
+          echo "Missing 'build-ic.tar' file!"
+          exit 1
+      fi
+
       if grep -q "$TARGET" bazel-targets || grep -qF "//..." bazel-targets; then
-          gitlab-ci/tools/build-diff.sh "$PATH0" "$PATH1"
+          VERSION="$(git rev-parse HEAD)"
+
+          # PATH0
+          mkdir -p "$PATH0"
+          curl -sfS --retry 5 --retry-delay 10 \
+            "https://download.dfinity.systems/ic/$VERSION/$PATH0/SHA256SUMS" \
+            -o "$PATH0/SHA256SUMS"
+
+          # PATH1
+          tar -xf build-ic.tar
+
+          # ignore *.wasm.did files
+          sed -i -e '/.wasm.did/d' "$PATH0/SHA256SUMS" "$PATH1/SHA256SUMS"
+
+          # for hostos / guestos we only care about update-img
+          if [ "${DISKIMG:-}" != "true" ]; then
+              sed -i -e '/disk-img/d' "$PATH0/SHA256SUMS" "$PATH1/SHA256SUMS"
+          fi
+
+          if ! diff -u "$PATH0/SHA256SUMS" "$PATH1/SHA256SUMS"; then
+              set -x
+              cat build-ic/info
+              echo "Build Determinism Check Failed!"
+              echo "Contact IDX or investigate by yourself using diffoscope:"
+              echo " * [bazel-test-all]: curl -sfS https://download.dfinity.systems/ic/$VERSION/$PATH0/<artifact> -O"
+              echo " * [build-ic]: curl $(cat build-ic/url) -O"
+              echo "See info for pull the artifacts from both CI jobs above. Specify <artifact> based on logs (e.g. 'ic-admin.gz', 'disk-img.tar.zst')."
+              echo "Note that [build-ic] artifacts.tar contains all the build artifacts (binaries, canisters and IC images)."
+              set +x
+              exit 1
+          else
+              echo "Build Determinism Check Successful"
+          fi
       fi
 build-determinism-release:
   needs:
@@ -2016,6 +2044,7 @@ build-ic:
   artifacts:
     paths:
       - bazel-build-log*.json*
+      - build-ic.tar
     reports:
       dotenv:
         - nns.release.env
@@ -2090,27 +2119,19 @@ build-ic:
           find ./artifacts/icos -name '*.gz' -delete
       fi
 
-      # release binaries
-      [ -d artifacts/release ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/release" "${CI_JOB_NAME}/release"
-      # canister binaries
-      [ -d artifacts/canisters ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/canisters" "${CI_JOB_NAME}/canisters"
+      tar -cf artifacts.tar artifacts
+      URL="http://$(cat /ceph-s3-info/BUCKET_HOST)/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}"
+      curl --request PUT --upload-file artifacts.tar "${URL}/artifacts.tar"
 
-      # guestos images
-      [ -d artifacts/icos/guestos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/icos/guestos" "${CI_JOB_NAME}/guest-os"
-      # hostos images
-      [ -d artifacts/icos/hostos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/icos/hostos" "${CI_JOB_NAME}/host-os"
-      # setupos images
-      [ -d artifacts/icos/setupos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/icos/setupos" "${CI_JOB_NAME}/setup-os"
+      for DIR in release canisters icos/guestos icos/hostos icos/setupos; do
+          mkdir -p "build-ic/${DIR}/"
+          cp "artifacts/${DIR}/SHA256SUMS" "build-ic/${DIR}/"
+      done
+
+      EXTERNAL_URL="https://objects.$(echo "$NODE_NAME" | cut -d'-' -f1)-idx1.dfinity.network/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}/artifacts.tar"
+      echo -e "Node: ${NODE_NAME:-}\nURL: ${URL}\nExternal URL: ${EXTERNAL_URL}" >./build-ic/info
+      echo "${EXTERNAL_URL}" >./build-ic/url
+      tar -cf build-ic.tar build-ic
 
       # clean up
       bazel clean --expunge
@@ -2119,9 +2140,6 @@ build-ic:
       if [ -f /tmp/nns.release.env ]; then
           mv /tmp/nns.release.env .
       fi
-  tags:
-    - dfinity-ic
-    - bazel
   variables:
     BAZEL_COMMAND: build
     RUN_ON_DIFF_ONLY: 'true'
@@ -2129,6 +2147,7 @@ build-ic-release:
   artifacts:
     paths:
       - bazel-build-log*.json*
+      - build-ic.tar
     reports:
       dotenv:
         - nns.release.env
@@ -2200,27 +2219,19 @@ build-ic-release:
           find ./artifacts/icos -name '*.gz' -delete
       fi
 
-      # release binaries
-      [ -d artifacts/release ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/release" "${CI_JOB_NAME}/release"
-      # canister binaries
-      [ -d artifacts/canisters ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/canisters" "${CI_JOB_NAME}/canisters"
+      tar -cf artifacts.tar artifacts
+      URL="http://$(cat /ceph-s3-info/BUCKET_HOST)/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}"
+      curl --request PUT --upload-file artifacts.tar "${URL}/artifacts.tar"
 
-      # guestos images
-      [ -d artifacts/icos/guestos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/icos/guestos" "${CI_JOB_NAME}/guest-os"
-      # hostos images
-      [ -d artifacts/icos/hostos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/icos/hostos" "${CI_JOB_NAME}/host-os"
-      # setupos images
-      [ -d artifacts/icos/setupos ] && buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
-          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" \
-          "artifacts/icos/setupos" "${CI_JOB_NAME}/setup-os"
+      for DIR in release canisters icos/guestos icos/hostos icos/setupos; do
+          mkdir -p "build-ic/${DIR}/"
+          cp "artifacts/${DIR}/SHA256SUMS" "build-ic/${DIR}/"
+      done
+
+      EXTERNAL_URL="https://objects.$(echo "$NODE_NAME" | cut -d'-' -f1)-idx1.dfinity.network/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}/artifacts.tar"
+      echo -e "Node: ${NODE_NAME:-}\nURL: ${URL}\nExternal URL: ${EXTERNAL_URL}" >./build-ic/info
+      echo "${EXTERNAL_URL}" >./build-ic/url
+      tar -cf build-ic.tar build-ic
 
       # clean up
       bazel clean --expunge
@@ -2229,9 +2240,6 @@ build-ic-release:
       if [ -f /tmp/nns.release.env ]; then
           mv /tmp/nns.release.env .
       fi
-  tags:
-    - dfinity-ic
-    - bazel
 build-setupos-base:
   artifacts:
     paths:
