fix(build-ic): check if file exists

diff --git a/gitlab-ci/config/zz-generated-gitlab-ci.yaml b/gitlab-ci/config/zz-generated-gitlab-ci.yaml
--- a/gitlab-ci/config/zz-generated-gitlab-ci.yaml
+++ b/gitlab-ci/config/zz-generated-gitlab-ci.yaml
@@ -240,9 +240,12 @@
       URL="http://$(cat /ceph-s3-info/BUCKET_HOST)/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}"
       curl --request PUT --upload-file artifacts.tar "${URL}/artifacts.tar"
 
+      mkdir build-ic
       for DIR in release canisters icos/guestos icos/hostos icos/setupos; do
-          mkdir -p "build-ic/${DIR}/"
-          cp "artifacts/${DIR}/SHA256SUMS" "build-ic/${DIR}/"
+          if [ -e "artifacts/${DIR}/SHA256SUMS" ]; then
+              mkdir -p "build-ic/${DIR}/"
+              cp "artifacts/${DIR}/SHA256SUMS" "build-ic/${DIR}/"
+          fi
       done
 
       EXTERNAL_URL="https://objects.$(echo "$NODE_NAME" | cut -d'-' -f1)-idx1.dfinity.network/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}/artifacts.tar"
@@ -1776,14 +1779,14 @@ build-determinism:
           exit 1
       fi
 
-      # build-ic.tar with SHA256SUMS files is expected from build-ic CI job
-      if [ ! -e build-ic.tar ]; then
-          echo "Missing 'build-ic.tar' file!"
-          exit 1
-      fi
-
       if grep -q "$TARGET" bazel-targets || grep -qF "//..." bazel-targets; then
           VERSION="$(git rev-parse HEAD)"
+
+          # build-ic.tar with SHA256SUMS files is expected from build-ic CI job
+          if [ ! -e build-ic.tar ]; then
+              echo "Missing 'build-ic.tar' file!"
+              exit 1
+          fi
 
           # PATH0
           mkdir -p "$PATH0"
@@ -2123,9 +2126,12 @@ build-ic:
       URL="http://$(cat /ceph-s3-info/BUCKET_HOST)/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}"
       curl --request PUT --upload-file artifacts.tar "${URL}/artifacts.tar"
 
+      mkdir build-ic
       for DIR in release canisters icos/guestos icos/hostos icos/setupos; do
-          mkdir -p "build-ic/${DIR}/"
-          cp "artifacts/${DIR}/SHA256SUMS" "build-ic/${DIR}/"
+          if [ -e "artifacts/${DIR}/SHA256SUMS" ]; then
+              mkdir -p "build-ic/${DIR}/"
+              cp "artifacts/${DIR}/SHA256SUMS" "build-ic/${DIR}/"
+          fi
       done
 
       EXTERNAL_URL="https://objects.$(echo "$NODE_NAME" | cut -d'-' -f1)-idx1.dfinity.network/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}/artifacts.tar"
@@ -2223,9 +2229,12 @@ build-ic-release:
       URL="http://$(cat /ceph-s3-info/BUCKET_HOST)/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}"
       curl --request PUT --upload-file artifacts.tar "${URL}/artifacts.tar"
 
+      mkdir build-ic
       for DIR in release canisters icos/guestos icos/hostos icos/setupos; do
-          mkdir -p "build-ic/${DIR}/"
-          cp "artifacts/${DIR}/SHA256SUMS" "build-ic/${DIR}/"
+          if [ -e "artifacts/${DIR}/SHA256SUMS" ]; then
+              mkdir -p "build-ic/${DIR}/"
+              cp "artifacts/${DIR}/SHA256SUMS" "build-ic/${DIR}/"
+          fi
       done
 
       EXTERNAL_URL="https://objects.$(echo "$NODE_NAME" | cut -d'-' -f1)-idx1.dfinity.network/$(cat /ceph-s3-info/BUCKET_NAME)/${VERSION}/${CI_JOB_ID}/artifacts.tar"
