fix: Interrupt the boot if veritysetup fails
Currently, if veritysetup fails, the hook exits with code 1 but the line `echo "ROOT=/dev/mapper/vroot" >/conf/param.conf` is never reached. Therefore, the boot continues with taking the rootfs from the kernel args and is successful. This defeats the purpose of the integrity check.

diff --git a/ic-os/components/early-boot/initramfs-tools/guestos/scripts/init-premount/verity-root b/ic-os/components/early-boot/initramfs-tools/guestos/scripts/init-premount/verity-root
--- a/ic-os/components/early-boot/initramfs-tools/guestos/scripts/init-premount/verity-root
+++ b/ic-os/components/early-boot/initramfs-tools/guestos/scripts/init-premount/verity-root
@@ -29,7 +29,10 @@ done
 
 echo "Root hash: ${ROOT_HASH}"
 
-veritysetup open "${ROOT}" vroot "${ROOT}" "${ROOT_HASH}" --hash-offset 10603200512
+if ! veritysetup open "${ROOT}" vroot "${ROOT}" "${ROOT_HASH}" --hash-offset 10603200512; then
+    echo "Fatal: veritysetup failed"
+    panic
+fi
 
 echo "ROOT=/dev/mapper/vroot" >/conf/param.conf
 
