run on namespace-profile-ubuntu-24-04-big

diff --git a/.github/workflows/ci-main.yml b/.github/workflows/ci-main.yml
--- a/.github/workflows/ci-main.yml
+++ b/.github/workflows/ci-main.yml
@@ -173,7 +173,7 @@ jobs:
   bazel-test-all:
     name: Bazel Test All
     needs: [config]
-    runs-on: ubuntu-24-large
+    runs-on: *dind-large-setup
     container: *container-setup
     timeout-minutes: 150
     steps:
@@ -227,12 +227,6 @@ jobs:
             target_pattern_file=$(mktemp)
             trap "rm $target_pattern_file" INT TERM EXIT
             targets_args=()
-            if [[ '${{ needs.config.outputs.skip_icos }}' == 'true' ]]; then
-              targets_args+=("--skip_icos")
-            fi
-            if [[ '${{ needs.config.outputs.skip_system_tests }}' == 'true' ]]; then
-              targets_args+=("--skip_system_tests")
-            fi
             if [[ '${{ needs.config.outputs.skip_long_tests }}' == 'true' ]]; then
               targets_args+=("--skip_long_tests")
             fi
@@ -354,6 +348,107 @@ jobs:
         run: |
           # Clean up the output base for the next run
           sudo rm -rf /var/tmp/bazel-output
+
+  bazel-test-all-namespace:
+    name: Bazel Test All (Namespace)
+    runs-on: namespace-profile-ubuntu-24-04-big
+    if: github.repository == 'dfinity/ic' # only run on public repo, not private since Namespace runners are not configured there, so these CI jobs get stuck otherwise.
+    container: *container-setup
+    timeout-minutes: 150
+    steps:
+      - *checkout
+      - name: Set up Bazel cache
+        run: |
+          # Creates a bazelrc configuration fragment which tells bazel where the cache lives.
+          nsc bazel cache setup --bazelrc=/tmp/bazel-cache.bazelrc
+      - name: Run Bazel Commands (Namespace)
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          echo "Building as user: $(whoami)"
+          echo "Bazel version: $(bazel version)"
+
+          mkdir -p /tmp/zig-cache
+
+          # Determine bazel_args based on event type or branch name
+          bazel_args=(
+            --noworkspace_rc
+            --bazelrc=./bazel/conf/.bazelrc.build
+            --bazelrc=/tmp/bazel-cache.bazelrc
+
+            --config=lint # enable lint checks
+            --config=flaky_retry # auto retry eg systests
+            )
+          if [[ "$CI_EVENT_NAME" == 'merge_group' ]]; then
+              bazel_args+=( --test_timeout_filters=short,moderate --flaky_test_attempts=3 )
+          elif [[ $BRANCH_NAME =~ ^hotfix-.* ]]; then
+              bazel_args+=( --test_timeout_filters=short,moderate )
+          else
+              bazel_args+=( --keep_going )
+          fi
+
+          if [[ '${{ needs.config.outputs.release-build }}' == 'true' ]]; then
+            # make sure the version is stamped in
+            bazel_args+=( --config=stamped )
+          fi
+
+          # If there are targets to test, pass them as a file to bazel to avoid bash & the OS
+          # complaining about the argument list being too long.
+          target_pattern_file=$(mktemp)
+          trap "rm $target_pattern_file" INT TERM EXIT
+          targets_args=(
+            --skip_icos
+            --skip_system_tests
+          )
+          if [[ '${{ needs.config.outputs.skip_long_tests }}' == 'true' ]]; then
+            targets_args+=("--skip_long_tests")
+          fi
+          if [[ '${{ needs.config.outputs.skip_didc_checks }}' == 'true' ]]; then
+            targets_args+=("--skip_didc_checks")
+          fi
+          if [[ '${{ needs.config.outputs.skip_buf_checks }}' == 'true' ]]; then
+            targets_args+=("--skip_buf_checks")
+          fi
+          if [[ '${{ needs.config.outputs.diff_only }}' == 'true' ]]; then
+            targets_args+=(
+              '--base=${{ github.event.pull_request.base.sha }}'
+              '--head=${{ github.event.pull_request.head.sha }}'
+              )
+          fi
+
+          bazel_do() {
+            bazel_cmd="$1"
+
+            "${CI_PROJECT_DIR:-}"/ci/scripts/targets.py "$bazel_cmd" \
+                  "${targets_args[@]}" >"$target_pattern_file"
+
+            num_targets=$(wc <"$target_pattern_file" -l)
+            # if bazel targets is empty we don't need to run any tests
+            if [ "$num_targets" -eq 0 ]; then
+              echo "No bazel targets to $bazel_cmd"
+              return
+            fi
+
+            echo "${bazel_cmd}ing $num_targets targets ..."
+            # the target list can get quite big, so we wrap it in details/summary
+            {
+              echo '<details><summary>'"$bazel_cmd"' '"$num_targets"' targets</summary>';
+              echo
+              echo '```'
+              cat "$target_pattern_file"
+              echo '```'
+              echo
+              echo '</details>';
+            } >>"$GITHUB_STEP_SUMMARY"
+
+            echo "Running bazel command: $bazel_cmd"
+
+            bazel "$bazel_cmd" "${bazel_args[@]}" "--target_pattern_file=$target_pattern_file"
+          }
+
+          bazel_do build
+          bazel_do test
 
   # Build & test the arm64-linux variant of pocket-ic-server and makes
   # it available as a GHA artifact
